version: '3.8'

services:
  products:
    build:
      context: ./api_node
    container_name: products
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - appnet

  orders:
    build:
      context: ./api_python
    container_name: orders
    ports:
      - "5000:5000"
    depends_on:
      - products
      - db
      - redis
    networks:
      - appnet

  payment:
    build:
      context: ./api_php
    container_name: payment
    ports:
      - "4000:4000"
    depends_on:
      - orders
    networks:
      - appnet

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet: