services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskdb
    ports:
      - "3307:3306"
    networks:
      - app-network
  flask_api:
    build: ./python-api
    container_name: python_api
    ports:
      - "5000:5000"
    volumes:
      - "./python-api:/app"
    command: "python app.py"
    networks:
      - app-network
    depends_on:
      - mysql_db
    
  node_api:
      build:
        context: ./app_node
      ports:
        - "3000:3000"
      container_name: node-app
      volumes:
        - ./app_node:/app
         - /app/node_modules
      command: node app.js
      networks:
        - app-network

networks:
  app-network:
    driver: bridge